### PR TITLE
Update to the new coveralls api

### PR DESCRIPTION
**Pull request by rpless**
@florence review plz

### CODE REVIEW

**Comment by rpless** [comment]
The Coveralls call is failing here. But I can't remember if that's because its using the one in the package manager or its bootstrapping the built one in. If its the latter that's bad.

**Comment by florence** [comment]
It's using the one here, and it seems to be passing now.

Also LGTM.

**Comment by rpless** [comment]
ummm, I don't it is https://travis-ci.org/rpless/cover-coveralls/jobs/106893574#L422

**Comment by florence** [comment]
Weird 16.1 failed but 16.3 is fine: https://travis-ci.org/rpless/cover-coveralls/jobs/106893576#L320

**Comment by florence** [comment]
Oh wait NVM, the output was hidden.

Maybe coveralls is just broken RN?

**Comment by rpless** [comment]
Ugh. I'm gonna set this back to help wanted and take a look this weekend.

**Pull request closed without merging**
